// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.34003
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace WebMagic.Specifications.Features.RequiresWebDriver
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ServeMarkdownFilesFeature : Xunit.IUseFixture<ServeMarkdownFilesFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Serve markdown files.feature"
#line hidden
        
        public ServeMarkdownFilesFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Serve markdown files", "As a developer\nI want to serve markdown files as easily as I can serve html files" +
                    " or mvc views", ProgrammingLanguage.CSharp, new string[] {
                        "web"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SetFixture(ServeMarkdownFilesFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.Extensions.TheoryAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Serve markdown files")]
        [Xunit.TraitAttribute("Description", "Correct Url is used")]
        [Xunit.Extensions.InlineDataAttribute("MarkdownEmptyAspNetWebApplication", "/", "<h1>/index.md</h1>", new string[0])]
        [Xunit.Extensions.InlineDataAttribute("MarkdownEmptyAspNetWebApplication", "/index", "<h1>/index.md</h1>", new string[0])]
        [Xunit.Extensions.InlineDataAttribute("MarkdownEmptyAspNetWebApplication", "/readme", "<h1>Markdown.EmptyAspNetWebApplication</h1>", new string[0])]
        [Xunit.Extensions.InlineDataAttribute("MarkdownEmptyAspNetWebApplication", "/directory-test", "<h1>/directory-test/index.md</h1>", new string[0])]
        [Xunit.Extensions.InlineDataAttribute("MarkdownEmptyAspNetWebApplication", "/directory-test/", "<h1>/directory-test/index.md</h1>", new string[0])]
        [Xunit.Extensions.InlineDataAttribute("MarkdownEmptyAspNetWebApplication", "/directory-test/index", "<h1>/directory-test/index.md</h1>", new string[0])]
        [Xunit.Extensions.InlineDataAttribute("MarkdownEmptyAspNetWebApplication", "/directory-test/file", "<h1>/directory-test/file.md</h1>", new string[0])]
        public virtual void CorrectUrlIsUsed(string websiteName, string url, string heading, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Correct Url is used", exampleTags);
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given(string.Format("the website is {0}", websiteName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
 testRunner.When(string.Format("I visit {0}", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
 testRunner.Then(string.Format("the page should include {0}", heading), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 10
 testRunner.And("the page is rendered with a layout page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ServeMarkdownFilesFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ServeMarkdownFilesFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
