// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.34003
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace WebMagic.Specifications.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class StringExtensionsFeature : Xunit.IUseFixture<StringExtensionsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "String extensions.feature"
#line hidden
        
        public StringExtensionsFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "String extensions", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SetFixture(StringExtensionsFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.Extensions.TheoryAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "String extensions")]
        [Xunit.TraitAttribute("Description", "string.AddLeadingDot()")]
        [Xunit.Extensions.InlineDataAttribute(".txt", ".txt", new string[0])]
        [Xunit.Extensions.InlineDataAttribute("txt", ".txt", new string[0])]
        [Xunit.Extensions.InlineDataAttribute(".txt.", ".txt.", new string[0])]
        [Xunit.Extensions.InlineDataAttribute("txt.", ".txt.", new string[0])]
        public virtual void String_AddLeadingDot(string @string, string expected, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("string.AddLeadingDot()", exampleTags);
#line 3
this.ScenarioSetup(scenarioInfo);
#line 4
 testRunner.When(string.Format("I call {0}.AddLeadingDot()", @string), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 5
 testRunner.Then(string.Format("{0} string should be returned", expected), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.Extensions.TheoryAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "String extensions")]
        [Xunit.TraitAttribute("Description", "string.RemoveLeadingDot()")]
        [Xunit.Extensions.InlineDataAttribute(".txt", "txt", new string[0])]
        [Xunit.Extensions.InlineDataAttribute("txt", "txt", new string[0])]
        [Xunit.Extensions.InlineDataAttribute(".txt.", "txt.", new string[0])]
        [Xunit.Extensions.InlineDataAttribute("txt.", "txt.", new string[0])]
        public virtual void String_RemoveLeadingDot(string @string, string expected, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("string.RemoveLeadingDot()", exampleTags);
#line 13
this.ScenarioSetup(scenarioInfo);
#line 14
 testRunner.When(string.Format("I call {0}.RemoveLeadingDot()", @string), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 15
 testRunner.Then(string.Format("{0} string should be returned", expected), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                StringExtensionsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                StringExtensionsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
